apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devenvironment
  description: Sin descripción
  annotations:
    github.com/project-slug: crlsquilumba/devenvironment
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
